version: '2'
services:
    squad_goals-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/squad_goals/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=squad_goals
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
